and split it up again. I see a pattern here ...

diff --git a/bigboards-updater/src/20140914/files/etc/init.d/networking b/bigboards-updater/src/20140914/files/etc/init.d/networking
--- a/bigboards-updater/src/20140914/files/etc/init.d/networking
+++ b/bigboards-updater/src/20140914/files/etc/init.d/networking
@@ -1,202 +1,136 @@
-#!/bin/sh -e
-### BEGIN INIT INFO
-# Provides:          networking ifupdown
-# Required-Start:    mountkernfs $local_fs urandom
-# Required-Stop:     $local_fs
-# Default-Start:     S
-# Default-Stop:      0 6
-# Short-Description: Raise network interfaces.
-# Description:       Prepare /run/network directory, ifstate file and raise network interfaces, or take them down.
-### END INIT INFO
+#!/bin/bash
+# Network Interface Script to bring Red Hat compatibility to Ubuntu
+# Copyright (c) 2013 Matt Martz and Rackspace US, Inc.
+# All Rights Reserved.
+#
+#    Licensed under the Apache License, Version 2.0 (the "License"); you may
+#    not use this file except in compliance with the License. You may obtain
+#    a copy of the License at
+#
+#         http://www.apache.org/licenses/LICENSE-2.0
+#
+#    Unless required by applicable law or agreed to in writing, software
+#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
+#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
+#    License for the specific language governing permissions and limitations
+#    under the License.
 
-PATH="/sbin:/bin"
-RUN_DIR="/run/network"
-IFSTATE="$RUN_DIR/ifstate"
-
-[ -x /sbin/ifup ] || exit 0
-[ -x /sbin/ifdown ] || exit 0
-
-. /lib/lsb/init-functions
-
-# Make sure that it's clear to the user that they shouldn't use this
-# script under upstart
-if init_is_upstart; then
-	echo "ERROR: Calling a sysvinit script on a system using upstart isn't supported. Please use the 'service' command instead."
-	exit 1
+RES_COL=60
+MOVE_TO_COL="echo -en \\033[${RES_COL}G"
+BOOTUP='color'
+SETCOLOR_SUCCESS="echo -en \\033[1;32m"
+SETCOLOR_FAILURE="echo -en \\033[1;31m"
+SETCOLOR_WARNING="echo -en \\033[1;33m"
+SETCOLOR_NORMAL="echo -en \\033[0;39m"
+if [ "$CONSOLETYPE" = "serial" ]; then
+	MOVE_TO_COL=
+	BOOTUP='serial'
+	SETCOLOR_SUCCESS=
+	SETCOLOR_FAILURE=
+	SETCOLOR_WARNING=
+	SETCOLOR_NORMAL=
 fi
 
-CONFIGURE_INTERFACES=yes
-EXCLUDE_INTERFACES=
-VERBOSE=no
-
-[ -f /etc/default/networking ] && . /etc/default/networking
-
-verbose=""
-[ "$VERBOSE" = yes ] && verbose=-v
-
-process_exclusions() {
-    set -- $EXCLUDE_INTERFACES
-    exclusions=""
-    for d
-    do
-	exclusions="-X $d $exclusions"
-    done
-    echo $exclusions
+echo_success() {
+	[ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+	echo -n "["
+	[ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
+	echo -n $"  OK  "
+	[ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+	echo -n "]"
+	echo -ne "\r"
+	return 0
 }
 
-process_options() {
-    [ -e /etc/network/options ] || return 0
-    log_warning_msg "/etc/network/options still exists and it will be IGNORED! Please use /etc/sysctl.conf instead."
+echo_failure() {
+	[ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+	echo -n "["
+	[ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+	echo -n $"FAILED"
+	[ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+	echo -n "]"
+	echo -ne "\r"
+	return 1
 }
 
-check_ifstate() {
-    if [ ! -d "$RUN_DIR" ] ; then
-	if ! mkdir -p "$RUN_DIR" ; then
-	    log_failure_msg "can't create $RUN_DIR"
-	    exit 1
-	fi
-    fi
-    if [ ! -r "$IFSTATE" ] ; then
-	if ! :> "$IFSTATE" ; then
-	    log_failure_msg "can't initialise $IFSTATE"
-	    exit 1
-	fi
-    fi
+get_iface_list() {
+	local IFACES
+	IFACES=(`ifquery --list -e lo`)
+	echo ${IFACES[*]}
 }
 
-check_network_file_systems() {
-    [ -e /proc/mounts ] || return 0
-
-    if [ -e /etc/iscsi/iscsi.initramfs ]; then
-	log_warning_msg "not deconfiguring network interfaces: iSCSI root is mounted."
-	exit 0
-    fi
-
-    while read DEV MTPT FSTYPE REST; do
-	case $DEV in
-	/dev/nbd*|/dev/nd[a-z]*|/dev/etherd/e*)
-	    log_warning_msg "not deconfiguring network interfaces: network devices still mounted."
-	    exit 0
-	    ;;
-	esac
-	case $FSTYPE in
-	nfs|nfs4|smbfs|ncp|ncpfs|cifs|coda|ocfs2|gfs|pvfs|pvfs2|fuse.httpfs|fuse.curlftpfs)
-	    log_warning_msg "not deconfiguring network interfaces: network file systems still mounted."
-	    exit 0
-	    ;;
-	esac
-    done < /proc/mounts
+order_array() {
+	local IFACES=($@)
+	IFACES=(`tr ' ' '\n' <<< "${IFACES[@]}" | sort -u`)
+	echo ${IFACES[*]}
 }
 
-check_network_swap() {
-    [ -e /proc/swaps ] || return 0
-
-    while read DEV MTPT FSTYPE REST; do
-	case $DEV in
-	/dev/nbd*|/dev/nd[a-z]*|/dev/etherd/e*)
-	    log_warning_msg "not deconfiguring network interfaces: network swap still mounted."
-	    exit 0
-	    ;;
-	esac
-    done < /proc/swaps
+order_array_reverse() {
+	local IFACES=($@)
+	IFACES=(`tr ' ' '\n' <<< "${IFACES[@]}" | sort -ru`)
+	echo ${IFACES[*]}
 }
 
-ifup_hotplug () {
-    if [ -d /sys/class/net ]
-    then
-	    ifaces=$(for iface in $(ifquery --list --allow=hotplug)
-			    do
-				    link=${iface##:*}
-				    link=${link##.*}
-				    if [ -e "/sys/class/net/$link" ] && [ "$(cat /sys/class/net/$link/operstate)" = up ]
-				    then
-					    echo "$iface"
-				    fi
-			    done)
-	    if [ -n "$ifaces" ]
-	    then
-		ifup $ifaces "$@" || true
-	    fi
-    fi
+down_interfaces() {
+	local IFACE rv1 rv2 rv3
+	for IFACE in $(order_array `get_iface_list`); do
+		echo -n "Shutting down interface $IFACE: "
+		ifconfig $IFACE down && ifdown --force $IFACE
+		rv1=$?
+		[[ ! $IFACE =~ ^bond ]] && ip addr flush $IFACE || true
+		rv2=$?
+		[[ $rv1 = 0 && $rv2 = 0 ]] && echo_success || echo_failure
+		echo
+	done
+	echo "Shutting down loopback interface: "
+	ifconfig lo down && ifdown --force lo && ip addr flush lo || false
+	rv=$?
+	[ $rv = 0 ] && echo_success || echo_failure
+	echo
 }
 
+up_interfaces() {
+	echo "Bringing up loopback interface: "
+	ifup lo
+	[ $? = 0 ] && echo_success || echo_failure
+	echo -n "Bringing up remaining interfaces: "
+	# This prevents an issue where ifup blocks waiting for "slave"
+	# interfaces or vice versa
+	ifup -a -e lo -e bond &
+	ifup -a -e lo -e eth
+	[ $? = 0 ] && echo_success || echo_failure
+	echo
+}
+
+# See how we were called.
 case "$1" in
-start)
-	if init_is_upstart; then
-		exit 1
-	fi
-	process_options
-	check_ifstate
+	start)
+		[ "$EUID" != "0" ] && exit 4
+		up_interfaces
+		rc=$?
+		;;
+	stop)
+		[ "$EUID" != "0" ] && exit 4
+		down_interfaces
+		rc=$?
+		;;
+	status)
+		echo $"Configured devices:"
+		echo lo `get_iface_list`
 
-	if [ "$CONFIGURE_INTERFACES" = no ]
-	then
-	    log_action_msg "Not configuring network interfaces, see /etc/default/networking"
-	    exit 0
-	fi
-	set -f
-	exclusions=$(process_exclusions)
-	log_action_begin_msg "Configuring network interfaces"
-	if ifup -a $exclusions $verbose && ifup_hotplug $exclusions $verbose
-	then
-	    log_action_end_msg $?
-	else
-	    log_action_end_msg $?
-	fi
-	;;
-
-stop)
-	if init_is_upstart; then
-		exit 0
-	fi
-	check_network_file_systems
-	check_network_swap
-
-	log_action_begin_msg "Deconfiguring network interfaces"
-	if ifdown -a --exclude=lo $verbose; then
-	    log_action_end_msg $?
-	else
-	    log_action_end_msg $?
-	fi
-	;;
-
-reload)
-	process_options
-
-	log_action_begin_msg "Reloading network interfaces configuration"
-	state=$(cat /run/network/ifstate)
-	ifdown -a --exclude=lo $verbose || true
-	if ifup --exclude=lo $state $verbose ; then
-	    log_action_end_msg $?
-	else
-	    log_action_end_msg $?
-	fi
-	;;
-
-force-reload|restart)
-	if init_is_upstart; then
-		exit 1
-	fi
-	process_options
-
-	log_warning_msg "Running $0 $1 is deprecated because it may not re-enable some interfaces"
-	log_action_begin_msg "Reconfiguring network interfaces"
-	ifdown -a --exclude=lo $verbose || true
-	set -f
-	exclusions=$(process_exclusions)
-	if ifup -a --exclude=lo $exclusions $verbose && ifup_hotplug $exclusions $verbose
-	then
-	    log_action_end_msg $?
-	else
-	    log_action_end_msg $?
-	fi
-	;;
-
-*)
-	echo "Usage: /etc/init.d/networking {start|stop|reload|restart|force-reload}"
-	exit 1
-	;;
+		echo $"Currently active devices:"
+		/sbin/ip -o link show up | awk -F ": " '{ printf "%s ", $2 }'
+		echo
+		;;
+	restart|reload|force-reload)
+		[ "$EUID" != "0" ] && exit 4
+		down_interfaces
+		up_interfaces
+		rc=$?
+		;;
+	*)
+		echo $"Usage: $0 {start|stop|status|restart|reload|force-reload}"
+		exit 2
 esac
 
-exit 0
-
-# vim: noet ts=8
+exit $rc
